[package]
name = "edolib-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0"
thiserror = "2.0"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
